services:
  App\EventListener\UserActivityListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }